<?php

namespace Database\Seeders;

use App\Models\Agreement;
use App\Models\Country;
use App\Models\Department;
use App\Models\Event;
use App\Models\EventType;
use App\Models\PartnerOrganization;
use App\Models\User;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Seed the application's events.
     */
    public function run(): void
    {
        $countryIds = Country::query()->pluck('id', 'iso3');
        $eventTypeIds = EventType::query()->pluck('id', 'name_uz');
        $partnerOrganizationIds = PartnerOrganization::query()->pluck('id', 'name_uz');
        $userIds = User::query()->pluck('id', 'phone');
        $departmentIds = Department::query()->pluck('id', 'code');
        $agreementsByCountry = Agreement::query()->get(['id', 'country_id'])->groupBy('country_id');

        $events = [
            [
                'country_iso3' => 'KAZ',
                'event_type_name' => 'Seminar',
                'partner_organization_name' => "Qozog'iston Respublikasi Ichki ishlar vazirligi",
                'responsible_user_phone' => '998900000001',
                'responsible_department_code' => 'XAB',
                'title_ru' => 'Международный семинар по обмену оперативным опытом',
                'title_uz' => "Tezkor tajriba almashinuvi bo'yicha xalqaro seminar",
                'title_cryl' => 'Тезкор тажриба алмашинуви бўйича халқаро семинар',
                'city' => 'Toshkent',
                'address' => 'Milliy gvardiya akademiyasi',
                'latitude' => 41.3110810,
                'longitude' => 69.2405620,
                'start_datetime' => '2026-04-12 10:00:00',
                'end_datetime' => '2026-04-12 17:00:00',
                'format' => 'offline',
                'status' => 'rejada',
                'description' => "Seminar davomida zamonaviy yondashuvlar va amaliy holatlar ko'rib chiqiladi.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-04-20',
            ],
            [
                'country_iso3' => 'TUR',
                'event_type_name' => 'Konferensiya',
                'partner_organization_name' => 'Jandarmeriya va Sohil qoriqlash akademiyasi',
                'responsible_user_phone' => '998900000004',
                'responsible_department_code' => 'HQB',
                'title_ru' => 'Конференция по вопросам подготовки кадров',
                'title_uz' => 'Kadrlar tayyorlash masalalari bo`yicha konferensiya',
                'title_cryl' => 'Кадрлар тайёрлаш масалалари бўйича конференция',
                'city' => 'Anqara',
                'address' => 'JSGA konferensiya zali',
                'latitude' => 39.9207700,
                'longitude' => 32.8541100,
                'start_datetime' => '2026-02-18 09:30:00',
                'end_datetime' => '2026-02-18 16:30:00',
                'format' => 'gibrid',
                'status' => 'tugatilgan',
                'description' => "Konferensiyada qo`shma o`quv kurslari va almashinuv dasturlari muhokama qilindi.",
                'result_summary_ru' => 'Подписан протокол о расширении обменных программ.',
                'result_summary_uz' => "Almashinuv dasturlarini kengaytirish bo`yicha protokol imzolandi.",
                'result_summary_cryl' => 'Алмашинув дастурларини кенгайтириш бўйича протокол имзоланди.',
                'control_due_date' => '2026-03-01',
            ],
            [
                'country_iso3' => 'KGZ',
                'event_type_name' => 'Forum',
                'partner_organization_name' => "Qirg'iz Respublikasi Elchixonasi",
                'responsible_user_phone' => '998900000002',
                'responsible_department_code' => 'XAB',
                'title_ru' => 'Форум дружественного сотрудничества',
                'title_uz' => 'Do`stona hamkorlik forumi',
                'title_cryl' => 'Дўстона ҳамкорлик форуми',
                'city' => 'Toshkent',
                'address' => 'Xalqaro forumlar saroyi',
                'latitude' => 41.2995000,
                'longitude' => 69.2401000,
                'start_datetime' => '2026-03-05 11:00:00',
                'end_datetime' => '2026-03-05 15:30:00',
                'format' => 'offline',
                'status' => 'hozirda',
                'description' => "Forum doirasida ikki tomonlama hamkorlikning yangi yo`nalishlari muhokama qilinmoqda.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-03-10',
            ],
            [
                'country_iso3' => 'CHN',
                'event_type_name' => 'Davra suhbati',
                'partner_organization_name' => 'Pekin jamoat xavfsizligi universiteti',
                'responsible_user_phone' => '998900000012',
                'responsible_department_code' => 'HQB',
                'title_ru' => 'Круглый стол по цифровой безопасности',
                'title_uz' => 'Raqamli xavfsizlik bo`yicha davra suhbati',
                'title_cryl' => 'Рақамли хавфсизлик бўйича давра суҳбати',
                'city' => 'Pekin',
                'address' => 'PPSU media markazi',
                'latitude' => 39.9042000,
                'longitude' => 116.4074000,
                'start_datetime' => '2026-05-19 14:00:00',
                'end_datetime' => '2026-05-19 17:00:00',
                'format' => 'online',
                'status' => 'rejada',
                'description' => "Mutaxassislar xavfsizlik monitoringi va tahlil platformalari yuzasidan tajriba almashadi.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-05-25',
            ],
            [
                'country_iso3' => 'RUS',
                'event_type_name' => 'Ishchi uchrashuv',
                'partner_organization_name' => 'Milliy gvardiya federal xizmati',
                'responsible_user_phone' => '998900000007',
                'responsible_department_code' => 'KB',
                'title_ru' => 'Рабочая встреча по итогам совместных мероприятий',
                'title_uz' => 'Qo`shma tadbirlar yakunlari bo`yicha ishchi uchrashuv',
                'title_cryl' => 'Қўшма тадбирлар якунлари бўйича ишчи учрашув',
                'city' => 'Moskva',
                'address' => 'Rosgvardiya shtabi',
                'latitude' => 55.7558000,
                'longitude' => 37.6173000,
                'start_datetime' => '2026-01-28 10:30:00',
                'end_datetime' => '2026-01-28 12:00:00',
                'format' => 'gibrid',
                'status' => 'tugatilgan',
                'description' => "Uchrashuvda o`tgan davr natijalari sarhisob qilindi.",
                'result_summary_ru' => 'Согласован перечень приоритетных задач на следующий квартал.',
                'result_summary_uz' => "Keyingi chorak uchun ustuvor vazifalar ro`yxati kelishildi.",
                'result_summary_cryl' => 'Кейинги чорак учун устувор вазифалар рўйхати келишилди.',
                'control_due_date' => '2026-02-05',
            ],
            [
                'country_iso3' => 'KAZ',
                'event_type_name' => 'Forum',
                'partner_organization_name' => "Qozog'iston Respublikasi Ichki ishlar vazirligi",
                'responsible_user_phone' => '998900000010',
                'responsible_department_code' => 'XAB',
                'title_ru' => 'Форум переводчиков и аналитиков',
                'title_uz' => 'Tarjimonlar va tahlilchilar forumi',
                'title_cryl' => 'Таржимонлар ва таҳлилчилар форуми',
                'city' => 'Astana',
                'address' => 'Hamkorlik markazi',
                'latitude' => 51.1694000,
                'longitude' => 71.4491000,
                'start_datetime' => '2026-06-03 09:00:00',
                'end_datetime' => '2026-06-03 18:00:00',
                'format' => 'offline',
                'status' => 'rejada',
                'description' => "Forum tarjima, hujjatlashtirish va tahliliy yondashuvlar bo`yicha sessiyalarni o`z ichiga oladi.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-06-10',
            ],
            [
                'country_iso3' => 'KGZ',
                'event_type_name' => 'Seminar',
                'partner_organization_name' => "Qirg'iz Respublikasi Elchixonasi",
                'responsible_user_phone' => '998900000003',
                'responsible_department_code' => 'XAB',
                'title_ru' => 'Семинар по церемониальному протоколу',
                'title_uz' => 'Marosim protokoli bo`yicha seminar',
                'title_cryl' => 'Маросим протоколи бўйича семинар',
                'city' => 'Toshkent',
                'address' => 'Protokol markazi',
                'latitude' => 41.3123000,
                'longitude' => 69.2787000,
                'start_datetime' => '2026-03-14 13:00:00',
                'end_datetime' => '2026-03-14 16:00:00',
                'format' => 'online',
                'status' => 'bekorlangan',
                'description' => "Texnik sabablarga ko`ra seminar masofaviy shaklda o`tkazilishi rejalashtirilgan edi.",
                'result_summary_ru' => 'Мероприятие перенесено на более позднюю дату.',
                'result_summary_uz' => "Tadbir keyingi muddatga ko`chirildi.",
                'result_summary_cryl' => 'Тадбир кейинги муддатга кўчирилди.',
                'control_due_date' => null,
            ],
            [
                'country_iso3' => 'CHN',
                'event_type_name' => 'Konferensiya',
                'partner_organization_name' => 'Pekin jamoat xavfsizligi universiteti',
                'responsible_user_phone' => '998900000020',
                'responsible_department_code' => 'HQB',
                'title_ru' => 'Конференция по технологиям ситуационного мониторинга',
                'title_uz' => 'Situatsion monitoring texnologiyalari bo`yicha konferensiya',
                'title_cryl' => 'Ситуацион мониторинг технологиялари бўйича конференция',
                'city' => 'Pekin',
                'address' => 'PPSU katta zal',
                'latitude' => 39.9070000,
                'longitude' => 116.3910000,
                'start_datetime' => '2026-07-08 10:00:00',
                'end_datetime' => '2026-07-08 17:30:00',
                'format' => 'gibrid',
                'status' => 'rejada',
                'description' => "Konferensiyada sun`iy intellekt va real vaqt monitoringi muhokama qilinadi.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-07-15',
            ],
            [
                'country_iso3' => 'TUR',
                'event_type_name' => 'Davra suhbati',
                'partner_organization_name' => 'Jandarmeriya va Sohil qoriqlash akademiyasi',
                'responsible_user_phone' => '998900000014',
                'responsible_department_code' => 'KB',
                'title_ru' => 'Круглый стол по архивной политике',
                'title_uz' => 'Arxiv siyosati bo`yicha davra suhbati',
                'title_cryl' => 'Архив сиёсати бўйича давра суҳбати',
                'city' => 'Anqara',
                'address' => 'Arxiv markazi',
                'latitude' => 39.9334000,
                'longitude' => 32.8597000,
                'start_datetime' => '2026-02-25 15:00:00',
                'end_datetime' => '2026-02-25 17:00:00',
                'format' => 'offline',
                'status' => 'tugatilgan',
                'description' => "Hujjatlar almashinuvi va saqlash standartlari yuzasidan tajriba almashildi.",
                'result_summary_ru' => 'Подготовлены предложения по цифровизации архивного фонда.',
                'result_summary_uz' => "Arxiv fondini raqamlashtirish bo`yicha takliflar tayyorlandi.",
                'result_summary_cryl' => 'Архив фондини рақамлаштириш бўйича таклифлар тайёрланди.',
                'control_due_date' => '2026-03-05',
            ],
            [
                'country_iso3' => 'RUS',
                'event_type_name' => 'Ishchi uchrashuv',
                'partner_organization_name' => 'Milliy gvardiya federal xizmati',
                'responsible_user_phone' => '998900000016',
                'responsible_department_code' => 'XAB',
                'title_ru' => 'Рабочая встреча по мониторингу рисков',
                'title_uz' => 'Xatarlarni monitoring qilish bo`yicha ishchi uchrashuv',
                'title_cryl' => 'Хатарларни мониторинг қилиш бўйича ишчи учрашув',
                'city' => 'Toshkent',
                'address' => 'Tahliliy markaz',
                'latitude' => 41.3205000,
                'longitude' => 69.2870000,
                'start_datetime' => '2026-03-21 10:00:00',
                'end_datetime' => '2026-03-21 12:30:00',
                'format' => 'online',
                'status' => 'hozirda',
                'description' => "Uchrashuvda ehtimoliy xavf indikatorlari va javob choralari ko`rib chiqilmoqda.",
                'result_summary_ru' => null,
                'result_summary_uz' => null,
                'result_summary_cryl' => null,
                'control_due_date' => '2026-03-25',
            ],
        ];

        foreach ($events as $eventData) {
            $countryId = $countryIds[$eventData['country_iso3']] ?? null;

            if (! $countryId) {
                continue;
            }

            $responsibleUserId = $userIds[$eventData['responsible_user_phone']] ?? null;
            $agreementId = $agreementsByCountry[$countryId][0]->id ?? null;

            Event::query()->updateOrCreate(
                [
                    'country_id' => $countryId,
                    'title_uz' => $eventData['title_uz'],
                    'start_datetime' => $eventData['start_datetime'],
                ],
                [
                    'title_ru' => $eventData['title_ru'],
                    'title_cryl' => $eventData['title_cryl'],
                    'event_type_id' => $eventTypeIds[$eventData['event_type_name']] ?? null,
                    'partner_organization_id' => $partnerOrganizationIds[$eventData['partner_organization_name']] ?? null,
                    'agreement_id' => $agreementId,
                    'city' => $eventData['city'],
                    'address' => $eventData['address'],
                    'latitude' => $eventData['latitude'],
                    'longitude' => $eventData['longitude'],
                    'end_datetime' => $eventData['end_datetime'],
                    'format' => $eventData['format'],
                    'status' => $eventData['status'],
                    'responsible_user_id' => $responsibleUserId,
                    'responsible_department_id' => $departmentIds[$eventData['responsible_department_code']] ?? null,
                    'description' => $eventData['description'],
                    'result_summary_ru' => $eventData['result_summary_ru'],
                    'result_summary_uz' => $eventData['result_summary_uz'],
                    'result_summary_cryl' => $eventData['result_summary_cryl'],
                    'control_due_date' => $eventData['control_due_date'],
                    'created_by' => $responsibleUserId,
                    'updated_by' => $responsibleUserId,
                ]
            );
        }
    }
}
