<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Rank;
use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Seed the application's users.
     */
    public function run(): void
    {
        $departmentIds = Department::query()->pluck('id', 'code');
        $rankIds = Rank::query()->pluck('id', 'name_uz');

        $users = [
            [
                'first_name' => 'Akmal',
                'middle_name' => 'Rustamovich',
                'last_name' => 'Karimov',
                'phone' => '998900000001',
                'position_uz' => 'Bosh mutaxassis',
                'position_ru' => 'Главный специалист',
                'position_cryl' => 'Бош мутахассис',
                'department_code' => 'XAB',
                'rank_name' => 'Mayor',
                'role' => 'admin',
                'is_active' => true,
            ],
            [
                'first_name' => 'Dilshod',
                'middle_name' => 'Anvarovich',
                'last_name' => 'Toshpulatov',
                'phone' => '998900000002',
                'position_uz' => 'Yetakchi mutaxassis',
                'position_ru' => 'Ведущий специалист',
                'position_cryl' => 'Етакчи мутахассис',
                'department_code' => 'XAB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Madina',
                'middle_name' => 'Shuhratovna',
                'last_name' => 'Yusupova',
                'phone' => '998900000003',
                'position_uz' => 'Inspektor',
                'position_ru' => 'Инспектор',
                'position_cryl' => 'Инспектор',
                'department_code' => 'XAB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Sardor',
                'middle_name' => 'Bekzodovich',
                'last_name' => 'Raximov',
                'phone' => '998900000004',
                'position_uz' => 'Bo‘lim boshlig‘i',
                'position_ru' => 'Начальник отдела',
                'position_cryl' => 'Бўлим бошлиғи',
                'department_code' => 'HQB',
                'rank_name' => 'Mayor',
                'role' => 'admin',
                'is_active' => true,
            ],
            [
                'first_name' => 'Aziza',
                'middle_name' => 'Komilovna',
                'last_name' => 'Nazarova',
                'phone' => '998900000005',
                'position_uz' => 'Yuriskonsult',
                'position_ru' => 'Юрисконсульт',
                'position_cryl' => 'Юрисконсульт',
                'department_code' => 'HQB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Jahongir',
                'middle_name' => 'Ilhomovich',
                'last_name' => 'Qodirov',
                'phone' => '998900000006',
                'position_uz' => 'Katta inspektor',
                'position_ru' => 'Старший инспектор',
                'position_cryl' => 'Катта инспектор',
                'department_code' => 'HQB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Shahnoza',
                'middle_name' => 'Murodovna',
                'last_name' => 'Ergasheva',
                'phone' => '998900000007',
                'position_uz' => 'Kadrlar bo‘limi boshlig‘i',
                'position_ru' => 'Начальник отдела кадров',
                'position_cryl' => 'Кадрлар бўлими бошлиғи',
                'department_code' => 'KB',
                'rank_name' => 'Mayor',
                'role' => 'admin',
                'is_active' => true,
            ],
            [
                'first_name' => 'Ulugbek',
                'middle_name' => 'Davronovich',
                'last_name' => 'Sattorov',
                'phone' => '998900000008',
                'position_uz' => 'Kadrlar inspektori',
                'position_ru' => 'Инспектор по кадрам',
                'position_cryl' => 'Кадрлар инспектори',
                'department_code' => 'KB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Nilufar',
                'middle_name' => 'Baxtiyorovna',
                'last_name' => 'Usmonova',
                'phone' => '998900000009',
                'position_uz' => 'Mutaxassis',
                'position_ru' => 'Специалист',
                'position_cryl' => 'Мутахассис',
                'department_code' => 'KB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Bekzod',
                'middle_name' => 'Olimovich',
                'last_name' => 'Saidov',
                'phone' => '998900000010',
                'position_uz' => 'Tarjimon',
                'position_ru' => 'Переводчик',
                'position_cryl' => 'Таржимон',
                'department_code' => 'XAB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Feruza',
                'middle_name' => 'Sherzodovna',
                'last_name' => 'Hamidova',
                'phone' => '998900000011',
                'position_uz' => 'Referent',
                'position_ru' => 'Референт',
                'position_cryl' => 'Референт',
                'department_code' => 'XAB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => false,
            ],
            [
                'first_name' => 'Rustam',
                'middle_name' => 'Abdullayevich',
                'last_name' => 'Turgunov',
                'phone' => '998900000012',
                'position_uz' => 'Maslahatchi',
                'position_ru' => 'Советник',
                'position_cryl' => 'Маслаҳатчи',
                'department_code' => 'HQB',
                'rank_name' => 'Mayor',
                'role' => 'admin',
                'is_active' => true,
            ],
            [
                'first_name' => 'Mohira',
                'middle_name' => 'Akmalovna',
                'last_name' => 'Islomova',
                'phone' => '998900000013',
                'position_uz' => 'Katta yuriskonsult',
                'position_ru' => 'Старший юрисконсульт',
                'position_cryl' => 'Катта юрисконсульт',
                'department_code' => 'HQB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Jamshid',
                'middle_name' => 'Farruxovich',
                'last_name' => 'Mamatov',
                'phone' => '998900000014',
                'position_uz' => 'Arxiv bo‘yicha mutaxassis',
                'position_ru' => 'Специалист по архиву',
                'position_cryl' => 'Архив бўйича мутахассис',
                'department_code' => 'KB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Gulnoza',
                'middle_name' => 'Uktamovna',
                'last_name' => 'Rasulova',
                'phone' => '998900000015',
                'position_uz' => 'Ish yurituvchi',
                'position_ru' => 'Делопроизводитель',
                'position_cryl' => 'Иш юритувчи',
                'department_code' => 'KB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Sherzod',
                'middle_name' => 'Kamolovich',
                'last_name' => 'Rajabov',
                'phone' => '998900000016',
                'position_uz' => 'Monitoring inspektori',
                'position_ru' => 'Инспектор мониторинга',
                'position_cryl' => 'Мониторинг инспектори',
                'department_code' => 'XAB',
                'rank_name' => 'Mayor',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Malika',
                'middle_name' => 'Azamatovna',
                'last_name' => 'Tohirova',
                'phone' => '998900000017',
                'position_uz' => 'Tahlilchi',
                'position_ru' => 'Аналитик',
                'position_cryl' => 'Таҳлилчи',
                'department_code' => 'HQB',
                'rank_name' => 'Kapitan',
                'role' => 'operator',
                'is_active' => false,
            ],
            [
                'first_name' => 'Oybek',
                'middle_name' => 'Botirovich',
                'last_name' => 'Ortiqov',
                'phone' => '998900000018',
                'position_uz' => 'Axborot almashinuvi koordinatori',
                'position_ru' => 'Координатор обмена информацией',
                'position_cryl' => 'Ахборот алмашинуви координатори',
                'department_code' => 'XAB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Sevara',
                'middle_name' => 'Dilmurodovna',
                'last_name' => 'Normatova',
                'phone' => '998900000019',
                'position_uz' => 'Kadrlar bo‘yicha mutaxassis',
                'position_ru' => 'Специалист по кадрам',
                'position_cryl' => 'Кадрлар бўйича мутахассис',
                'department_code' => 'KB',
                'rank_name' => 'Mayor',
                'role' => 'operator',
                'is_active' => true,
            ],
            [
                'first_name' => 'Umid',
                'middle_name' => 'Javlonovich',
                'last_name' => 'Salimov',
                'phone' => '998900000020',
                'position_uz' => 'Mutaxassis',
                'position_ru' => 'Специалист',
                'position_cryl' => 'Мутахассис',
                'department_code' => 'HQB',
                'rank_name' => 'Leytenant',
                'role' => 'operator',
                'is_active' => true,
            ],
        ];

        foreach ($users as $userData) {
            $user = User::query()->updateOrCreate(
                ['phone' => $userData['phone']],
                [
                    'first_name' => $userData['first_name'],
                    'middle_name' => $userData['middle_name'],
                    'last_name' => $userData['last_name'],
                    'password' => 'password',
                    'position_uz' => $userData['position_uz'],
                    'position_ru' => $userData['position_ru'],
                    'position_cryl' => $userData['position_cryl'],
                    'department_id' => $departmentIds[$userData['department_code']] ?? null,
                    'rank_id' => $rankIds[$userData['rank_name']] ?? 1,
                    'is_active' => $userData['is_active'],
                ]
            );

            $user->syncRoles([$userData['role']]);
        }
    }
}
